ktor:
  application:
    modules:
      - com.github.SleekNekro.ApplicationKt.module
  deployment:
    port: 8085
    host: "0.0.0.0"
jwt:
  domain: "http://localhost:8085"
  audience: "jwt-audience"
  realm: "Acceso a la API"
  secret: "salypimienta"