ktor:
  application:
    modules:
      - com.github.SleekNekro.ApplicationKt.module
  deployment:
    port: 8085
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "Acceso a la API"
  secret: "salypimienta"