ktor:
  application:
    modules:
      - com.github.SleekNekro.ApplicationKt.module
  deployment:
    port: ${PORT}  # Usa el valor de PORT, o 8085 si no existe (útil para desarrollo local)
    host: "0.0.0.0"      # Permite conexiones externas
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "Acceso a la API"
  secret: "salypimienta"